server {
    listen 80;
    server_name for66bit.ru www.for66bit.ru;
    
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name for66bit.ru www.for66bit.ru;

    ssl_certificate /etc/letsencrypt/live/for66bit.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/for66bit.ru/privkey.pem;

    location /api/ {
        proxy_pass http://127.0.0.1:5020;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /hubs/ {
        proxy_pass http://127.0.0.1:5020;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
    }

    location / {
        proxy_pass http://127.0.0.1:5173;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
